#!/bin/bash

if ! command -v cz >/dev/null && [ "$DEVPOD" = "true" ]; then
  git config --global push.autoSetupRemote true
  git config --global --add safe.directory /workspaces/devops-study-app/
  pip install --user pipx
  pipx install commitizen
  pre-commit install
  pre-commit install --hook-type commit-msg
fi

if ! python -c "import anthropic" 2>/dev/null; then
  pip install -r linkedin/requirements.txt -r linkedin/requirements-dev.txt
fi
